spring:
  datasource:
    username: root
    password: Saadhvi03ss
    url: jdbc:mysql://localhost:3306/movies
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: saadhvi111@gmail.com
    password: jscagivkkrxdcvak
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"
